### ISSUE TITLE
WorkItem Links does not show up on when direct detail link is hit

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-planner#438] opened 2016-12-05 21:41 UTC
## Steps to reproduce

* Go to http://demo.almighty.io/work-item-list/detail/346
* No links are shown
* Select another WorkItem from the List
* Use back button to go back to the first WorkItem
* 64 links are shown (64 links are actually correct number according to DB)

Demo: https://youtu.be/sjAUbtMVrUM

**Comment by joshuawilson** [comment] 2016-12-05 21:42
@sanbornsen can you please take a look at this.

**Comment by debloper** [comment] 2016-12-22 11:06
Can't reproduce.

**Comment by sanbornsen** [comment] 2016-12-22 11:47
I think this issue is not there anymore. Got resolved with last set of update for linking.

**Comment by sanbornsen** [comment] 2016-12-22 11:49
@aslakknutsen can you verify and close the issue?

**Comment by nimishamukherjee** [comment] 2017-01-18 04:57
Closing as the issue has been fixed.

**Closed by nimishamukherjee** 2017-01-18 04:57 UTC
Labels: bug
