### ISSUE TITLE
Iteration Search components overlaps Assignee Search component

### ISSUE THREAD

**Issue by DhritiShikhar** [fabric8io/fabric8-planner#1704] opened 2017-04-20 09:23 UTC
How to reproduce?
1. Click on assignee search. This will give you a drop-down list of assignees
2. Click on iteration search bar

![screenshot from 2017-04-20 14-42-43](https://cloud.githubusercontent.com/assets/6303309/25223367/d69f384c-25d8-11e7-9593-93c2e9dd5d2a.png)

**Comment by naina-verma** [comment] 2017-04-20 10:48
@fabric8io/uxd can you please look into it !

**Comment by muruGanesan** [comment] 2017-04-20 15:41
@SMahil, Could you please check bug and close? please let us know if you need any help.

**Comment by joshuawilson** [comment] 2017-04-20 15:44
@muruGanesan why do you want her to close this? She is asking for help. If this was handled offline, please provide context.

**Comment by catrobson** [comment] 2017-04-20 15:58
@naina-verma - If the user selects the Iteration dropdown, the assignee dropdown should collapse and "cancel" back to original state, meaning you should never run into this overlapping issue.

**Comment by joshuawilson** [comment] 2017-04-20 16:01
I have to ask, @naina-verma were you asking for design clarification or for someone like @mindreeper2420 to actually just fix it?

**Comment by muruGanesan** [comment] 2017-04-20 17:17
@joshuawilson, As Catherine mentioned, this is an UI issue. Since Sukhvir and me are working on few UI bugs, I asked Sukhvir to fix this.

Anyway, I'll connect with Nina & UI deve-team tomorrow and close it ASAP.

**Comment by joshuawilson** [comment] 2017-04-20 17:21
@muruGanesan I'm confused. @catrobson didn't mention this as a UI issue. She explained the intended design.
If you are discussing this issue offline then you really should capture that context and add it here, the rest of us reading this can not follow.

**Comment by muruGanesan** [comment] 2017-04-20 17:32
@joshuawilson, let me find the appropriate place to capture the 'design intent"

**Comment by joshuawilson** [comment] 2017-04-20 18:36
@muruGanesan this is not a question of design. @catrobson confirmed the design. My confusion comes from your comments. 
I believe that @naina-verma raised an issue and wanted someone with CSS skills to fix it, that is most likely why she asked UXD.

**Comment by naina-verma** [comment] 2017-05-11 06:39
Verified !

**Closed by naina-verma** 2017-05-11 06:39 UTC
Labels: bug, bug fixed, important
